### ISSUE TITLE
Possible race condition

### ISSUE THREAD

**Issue by mblakele** [theogravity/svg-rasterizer#1]
I'm seeing an intermittent error running svg-rasterizer. In about 1% of runs I see an error like this:

```
Running "svg-rasterizer:default" (svg-rasterizer) task
00:41:08.021Z  INFO svg-rasterizer/lib: Using cache file { file: 'dist/svg-rasterizer-cache/68e467929bb534638321bf978e83105b51c04492.json' }
Warning: ENOENT: no such file or directory, mkdir '/Users/mblakele/Source/myproject/svg-rasterizer-tmp/aU1OvN' Use --force to continue.

Aborted due to warnings.
```

So far the error isn't reproducible: run the same task again and it works. I've only seen it twice so far, once on OS X and once on Linux. So it smells like a race condition.

**Comment by theogravity** [comment]
@mblakele states that `fs.ensureDir` should be `fs.ensureDirSync`
